nyt_list_reviews:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: postgres-dev
      port: 5432
      user: admin
      pass: admin
      dbname: mydb
      schema: nyt