version: '3.8'

services:
  # Python service
  python:
    image: python:3.8-slim
    container_name: python-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    ports:
      - "8888:8888"
    depends_on:
      - postgres-dev

  # PostgreSQL database service
  postgres-dev:
    image: postgres:13
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  # dbt service
  dbt:
    image: fishtownanalytics/dbt:1.0.0
    container_name: dbt-core
    environment:
      - DBT_PROFILES_DIR=/dbt/profiles
      - DBT_TARGET=dev
    volumes:
      - ./dbt:/dbt
      - ./dbt/profiles.yml:/dbt/profiles.yml
    depends_on:
      - postgres-dev
    working_dir: /dbt
    command: ["dbt", "run"]
  
  # Jupyter Notebook servic
  jupyter:
    image: jupyter/scipy-notebook:python-3.8
    container_name: jupyter-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    # depends_on:
    #   - python
