version: '3.8'

services:
  # Python service
  python:
    image: python:3.8-slim
    container_name: python-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  # PostgreSQL database service
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "5431:5432" # change port 5431 to allow astro postgres to listen on 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "80:80"
    depends_on:
      - postgres

  # Jupyter Notebook servic
  jupyter:
    image: jupyter/scipy-notebook:python-3.8
    container_name: jupyter-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - python
