version: 2

sources:
  - name: stage
    database: mydb
    schema: stage
    description: "Raw data layer"
    tables:
      - name: lists
        description: "Information about book lists"
        columns:
          - name: id
            description: "Unique identifier for the list"
            tests:
              # - uniques
              - not_null
          - name: list_name
            description: "Name of the list"
          - name: list_name_encoded
            description: "Encoded name of the list"
          - name: display_name
            description: "Display name of the list"
          - name: updated
            description: "Last updated date of the list"
            meta:
              type: datetime
          - name: list_image
            description: "Image associated with the list"
          - name: list_image_width
            description: "Width of the list image"
          - name: list_image_height
            description: "Height of the list image"

        # loaded_at_filed: updated
        # freshness:
        #   warn_after: {count: 500, period: day}
        #   error_after: {count: 800, period: day}
        #   # filter: datediff('day', updated, current_date)
      
      - name: best_sellings_lists_books
        description: "Information about best-selling books"
        columns:
          - name: id
            description: "Unique identifier for the best-seller record"
            #tests:
              # - unique
              #- not_null
          - name: bestsellers_date
            description: "Date when the list of best-sellers was published"
            tests:
              - not_null
          - name: published_date
            description: "Actual publication date of the book"
            meta:
              type: datetime
          - name: previous_published_date
            description: "Previous publication date of the book"
          - name: next_published_date
            description: "Next publication date of the book"
          - name: list_id
            description: "ID of the list the book belongs to"
          - name: book_id
            description: "ID of the book"
          - name: rank
            description: "Rank of the book in the best-seller list"
          - name: weeks_on_list
            description: "Number of weeks the book has been on the list"
          - name: price
            description: "Price of the book"

        # loaded_at_field: published_date
        # freshness:
        #   warn_after: {count: 500, period: day}
        #   error_after: {count: 800, period: day}
        

      - name: books
        description: "Details about the books"
        columns:
          - name: id
            description: "Unique identifier for the book"
            tests:
              #- unique
              - not_null
          - name: title
            description: "Title of the book"
          - name: publisher
            description: "Publisher of the book"
          - name: author
            description: "Author of the book"
          - name: contributor
            description: "Contributor of the book"
          - name: contributor_note
            description: "Notes about the book's contributors"
          - name: description
            description: "Description or summary of the book"
          - name: created_date
            description: "Date the book was created"
          - name: updated_date
            description: "Date the book details were last updated"
            meta:
              type: datetime
          - name: age_group
            description: "Age group for which the book is intended"
          - name: amazon_product_url
            description: "Amazon product URL for the book"
          - name: primary_isbn13
            description: "Primary ISBN-13 number of the book"
          - name: primary_isbn10
            description: "Primary ISBN-10 number of the book"
          - name: book_image_width
            description: "Width of the book's image"
          - name: book_image_height
            description: "Height of the book's image"
          - name: first_chapter_link
            description: "Link to the first chapter of the book"
          - name: book_uri
            description: "Unique URI for the book"
          - name: sunday_review_link
            description: "Link to the Sunday review of the book"

        # loaded_at_field: updated_date
        # freshness:
        #   warn_after: {count: 500, period: day}
        #   error_after: {count: 800, period: day}

      - name: books_buy_links
        description: "Buy links for the books"
        columns:
          - name: book_id
            description: "ID of the book"
            tests:
              # - unique
              - not_null
          - name: website_name
            description: "Name of the website selling the book"
          - name: website_url
            description: "URL to purchase the book from the website"
